# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
- task: UsePythonVersion@0
  condition: false
  inputs:
    versionSpec: '3.x'
    architecture: 'x64'

- bash: python -m pip install --upgrade pip
  condition: false
  displayName: 'Upgrade pip'
  
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
